/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.8.10"
    kotlin("plugin.serialization") version "1.8.21"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

val maelstromRuntime: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.9.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0")
    implementation(project(":protocol"))

    maelstromRuntime(project(mapOf("path" to ":maelstrom", "configuration" to "maelstromBin")))
}

application {
    // Define the main class for the application.
    mainClass.set("vortex.AppKt")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

enum class ChallengeOptions(val value: String) {
    A("--node-count 1 --time-limit 20 --rate 10"),
    B("--node-count 5 --time-limit 20 --rate 10"),
    C("--node-count 5 --time-limit 20 --rate 10 --nemesis partition"),
    D_AND_E("--node-count 25 --time-limit 20 --rate 100 --latency 100"),
    D_NEMESIS("--node-count 25 --time-limit 20 --rate 100 --latency 100 --nemesis partition"),
}

ChallengeOptions.values().forEach {
    tasks.register<Exec>("runMaelstrom#${it.name}") {
        dependsOn(maelstromRuntime.buildDependencies)
        dependsOn("installDist")
        val maelstromBin = maelstromRuntime.singleFile.path
        val nodeBin = "$buildDir/install/${project.name}/bin/${project.name}"
        val opts = it.value
        val cmd = "$maelstromBin test -w broadcast --bin $nodeBin $opts"
        commandLine("bash", "-c", cmd)
    }
}
